import mongoose from 'mongoose';

const payslipSchema = new mongoose.Schema({
  employeeId: { type: mongoose.Schema.Types.ObjectId, ref: 'Employee', required: true },
  tenantId: { type: mongoose.Schema.Types.ObjectId, ref: 'Tenant', required: true },
  period: { type: String, required: true, trim: true },
  payslipType: { type: String, enum: ['Regular', 'Bonus', 'Off-cycle'], default: 'Regular' },
  basicSalary: { type: Number, required: true, min: 0 },
  allowances: { type: Number, default: 0 },
  grossPay: { type: Number, default: 0 },
  deductions: {
    paye: { type: Number, default: 0 },
    pension: { type: Number, default: 0 },
    nhf: { type: Number, default: 0 },
    other: { type: Number, default: 0 },
    total: { type: Number, default: 0 },
  },
  netPay: { type: Number, required: true, min: 0 },
  // `status` = whether the payslip itself is finalized vs a draft. This is
  // separate from `payment` below, which tracks whether the net pay has
  // actually been disbursed via Paystack — a payslip can be 'Paid' (finalized)
  // while its payment is still 'Unpaid' (money not yet sent).
  status: { type: String, enum: ['Paid', 'Draft'], default: 'Draft' },

  // Payroll disbursement via Paystack. `reference` is generated by us and
  // encodes the tenantId so the public webhook can look up which tenant's
  // Paystack secret key to verify the signature with (see
  // controllers/webhookController.js).
  payment: {
    status: { type: String, enum: ['Unpaid', 'Processing', 'Pending_OTP', 'Paid', 'Failed'], default: 'Unpaid' },
    reference: { type: String },
    transferCode: { type: String },
    paidAt: { type: Date },
    failureReason: { type: String },
  },

  createdAt: { type: Date, default: Date.now },
});

payslipSchema.index({ 'payment.reference': 1 });

payslipSchema.index({ employeeId: 1, period: 1 }, { unique: true });
const Payslip = mongoose.model('Payslip', payslipSchema);
export default Payslip;
